# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afterlogin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!
#
# Copyright 2020 by Ajeng Fitria Rahmawati


from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtSql import *
from datetime import date
from main import *


class Ui_Dialog(QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(787, 550)
        #-----------label untuk get Id akun----------#
        self.labelId = QLabel()
        self.labelId.setText("")
        #--------------------------------------------#

        self.label_20 = QLabel(Dialog)
        self.label_20.setGeometry(QRect(-50, 0, 881, 551))
        font = QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 85, 127);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QLabel(Dialog)
        self.label_21.setGeometry(QRect(310, 10, 171, 51))
        font = QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_21.setObjectName("label_21")
        self.Home_2 = QTabWidget(Dialog)
        self.Home_2.setGeometry(QRect(0, 80, 791, 431))
        self.Home_2.setMinimumSize(QSize(791, 431))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Home_2.setFont(font)
        self.Home_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(85, 85, 255);")
        self.Home_2.setObjectName("Home_2")
        self.Home_5 = QWidget()
        self.Home_5.setObjectName("Home_5")
        self.label_42 = QLabel(self.Home_5)
        self.label_42.setGeometry(QRect(80, 20, 481, 41))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_42.setObjectName("label_42")
        self.label_43 = QLabel(self.Home_5)
        self.label_43.setGeometry(QRect(80, 170, 161, 20))
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")

        #-----------tampilan table lowongan----------#
        self.tLowongan = QTableWidget(self.Home_5)
        self.tLowongan.setGeometry(QRect(80, 70, 621, 261))
        font = QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(75)
        self.tLowongan.setFont(font)
        self.tLowongan.setStyleSheet("color: rgb(85, 85, 255);\n"
"background-color: rgb(227, 227, 227);")
        self.tLowongan.setRowCount(11)
        self.tLowongan.setColumnCount(6)
        self.tLowongan.setObjectName("tLowongan")
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(10, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(5, item)

        #-----------tampilan tab data profile----------#
        self.Home_2.addTab(self.Home_5, "")
        self.Profile = QWidget()
        self.Profile.setObjectName("Profile")
        self.label_44 = QLabel(self.Profile)
        self.label_44.setGeometry(QRect(30, 40, 101, 91))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_44.setObjectName("label_44")
        self.layoutWidget_5 = QWidget(self.Profile)
        self.layoutWidget_5.setGeometry(QRect(140, 40, 301, 303))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_7 = QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_45 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 4, 0, 1, 1)
        self.label_46 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 5, 0, 1, 1)
        self.label_47 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_47.setObjectName("label_47")
        self.gridLayout_7.addWidget(self.label_47, 3, 0, 1, 1)
        self.radL = QRadioButton(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(75)
        self.radL.setFont(font)
        self.radL.setStyleSheet("color: rgb(255, 255, 255);")
        self.radL.setObjectName("radL")
        self.gridLayout_7.addWidget(self.radL, 5, 2, 1, 1)
        self.radP = QRadioButton(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(75)
        self.radP.setFont(font)
        self.radP.setStyleSheet("color: rgb(255, 255, 255);")
        self.radP.setObjectName("radP")
        self.gridLayout_7.addWidget(self.radP, 5, 1, 1, 1)
        self.pAlamat = QTextEdit(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pAlamat.setFont(font)
        self.pAlamat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pAlamat.setObjectName("pAlamat")
        self.gridLayout_7.addWidget(self.pAlamat, 2, 1, 1, 2)
        self.label_48 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_48.setObjectName("label_48")
        self.gridLayout_7.addWidget(self.label_48, 1, 0, 1, 1)
        self.pPassword = QLineEdit(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pPassword.setFont(font)
        self.pPassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pPassword.setObjectName("pPassword")
        self.gridLayout_7.addWidget(self.pPassword, 3, 1, 1, 2)
        self.label_49 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_50 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 2, 0, 1, 1)
        self.pNama = QLineEdit(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pNama.setFont(font)
        self.pNama.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pNama.setText("")
        self.pNama.setObjectName("pNama")
        self.gridLayout_7.addWidget(self.pNama, 0, 1, 1, 2)
        self.pEmail = QLineEdit(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pEmail.setFont(font)
        self.pEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pEmail.setObjectName("pEmail")
        self.gridLayout_7.addWidget(self.pEmail, 1, 1, 1, 2)
        self.pHp = QLineEdit(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pHp.setFont(font)
        self.pHp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pHp.setObjectName("pHp")
        self.gridLayout_7.addWidget(self.pHp, 4, 1, 1, 2)
        self.label_51 = QLabel(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 6, 0, 1, 1)
        self.pHp_2 = QLineEdit(self.layoutWidget_5)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pHp_2.setFont(font)
        self.pHp_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pHp_2.setObjectName("pHp_2")
        self.gridLayout_7.addWidget(self.pHp_2, 6, 1, 1, 2)
        self.btnSimpanProfile = QPushButton(self.Profile)
        self.btnSimpanProfile.setGeometry(QRect(580, 270, 152, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnSimpanProfile.setFont(font)
        self.btnSimpanProfile.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnSimpanProfile.setObjectName("btnSimpanProfile")
        ##------------------link edit profile---------------##
        self.btnSimpanProfile.clicked.connect(self.editProfile)

        self.layoutWidget_6 = QWidget(self.Profile)
        self.layoutWidget_6.setGeometry(QRect(470, 40, 258, 211))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_8 = QGridLayout(self.layoutWidget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_52 = QLabel(self.layoutWidget_6)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 0, 0, 1, 1)
        self.pPengalaman = QTextEdit(self.layoutWidget_6)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pPengalaman.setFont(font)
        self.pPengalaman.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pPengalaman.setObjectName("pPengalaman")
        self.gridLayout_8.addWidget(self.pPengalaman, 1, 0, 1, 1)
        self.label_53 = QLabel(self.layoutWidget_6)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 2, 0, 1, 1)
        self.pSkill = QTextEdit(self.layoutWidget_6)
        font = QFont()
        font.setFamily("Segoe UI")
        self.pSkill.setFont(font)
        self.pSkill.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pSkill.setObjectName("pSkill")
        self.gridLayout_8.addWidget(self.pSkill, 3, 0, 1, 1)

        #-----------tampilan tab submit lamaran----------#
        self.Home_2.addTab(self.Profile, "")
        self.Lamaran = QWidget()
        self.Lamaran.setObjectName("Lamaran")
        self.label_27 = QLabel(self.Lamaran)
        self.label_27.setGeometry(QRect(80, 90, 241, 231))
        self.label_27.setStyleSheet("image: url(img/signup.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.layoutWidget_7 = QWidget(self.Lamaran)
        self.layoutWidget_7.setGeometry(QRect(371, 112, 252, 101))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_9 = QGridLayout(self.layoutWidget_7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_55 = QLabel(self.layoutWidget_7)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_55.setObjectName("label_55")
        self.gridLayout_9.addWidget(self.label_55, 0, 0, 1, 1)
        self.subNo = QLineEdit(self.layoutWidget_7)
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.subNo.setFont(font)
        self.subNo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.subNo.setText("")
        self.subNo.setObjectName("subNo")
        self.gridLayout_9.addWidget(self.subNo, 0, 1, 1, 1)
        self.label_56 = QLabel(self.layoutWidget_7)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_56.setObjectName("label_56")
        self.gridLayout_9.addWidget(self.label_56, 1, 0, 1, 1)
        self.btnUnggahCV = QPushButton(self.layoutWidget_7)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        self.btnUnggahCV.setFont(font)
        self.btnUnggahCV.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnUnggahCV.setObjectName("btnUnggahCV")
        self.gridLayout_9.addWidget(self.btnUnggahCV, 1, 1, 1, 1)
        ##------------------link unggah cv---------------##
        self.btnUnggahCV.clicked.connect(self.loadCV)

        self.btnSubmitLamaran = QPushButton(self.layoutWidget_7)
        font = QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnSubmitLamaran.setFont(font)
        self.btnSubmitLamaran.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnSubmitLamaran.setObjectName("btnSubmitLamaran")
        self.gridLayout_9.addWidget(self.btnSubmitLamaran, 2, 0, 1, 2)
        ##------------------link submit lamaran---------------##
        self.btnSubmitLamaran.clicked.connect(self.addLamaran)

        self.label_57 = QLabel(self.Lamaran)
        self.label_57.setGeometry(QRect(370, 220, 251, 25))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_57.setObjectName("label_57")

        #-----------tampilan tab lamaran----------#
        self.Home_2.addTab(self.Lamaran, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_58 = QLabel(self.tab_3)
        self.label_58.setGeometry(QRect(80, 20, 451, 41))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_58.setObjectName("label_58")
        self.t_lamaran = QTableWidget(self.tab_3)
        self.t_lamaran.setGeometry(QRect(80, 70, 621, 261))
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(11)
        self.t_lamaran.setFont(font)
        self.t_lamaran.setStyleSheet("color: rgb(85, 85, 255);\n"
"background-color: rgb(227, 227, 227);")
        self.t_lamaran.setRowCount(11)
        self.t_lamaran.setColumnCount(6)
        self.t_lamaran.setObjectName("t_lamaran")
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(10, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setBold(False)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(5, item)
        self.Home_2.addTab(self.tab_3, "")
        self.btnLogout = QPushButton(Dialog)
        self.btnLogout.setGeometry(QRect(700, 80, 91, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(75)
        self.btnLogout.setFont(font)
        self.btnLogout.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.btnLogout.setObjectName("btnLogout")

        self.retranslateUi(Dialog)
        self.Home_2.setCurrentIndex(0)
        #-----------logout button----------#
        self.btnLogout.clicked.connect(Dialog.close)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_21.setText(_translate("Dialog", "LOKERINDO"))
        self.label_42.setText(_translate("Dialog", "Ayo, cari pekerjaan sesuai keahlian kamu di sini....!"))
        item = self.tLowongan.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "No"))
        item = self.tLowongan.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Posisi"))
        item = self.tLowongan.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Perusahaan"))
        item = self.tLowongan.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Penempatan"))
        item = self.tLowongan.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Gaji Ditawarkan"))
        item = self.tLowongan.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Max Submit"))
        #Tampil Data Lowongan
        self.loadLowongan(Dialog)
        ####

        self.Home_2.setTabText(self.Home_2.indexOf(self.Home_5), _translate("Dialog", "             Home          ", " "))
        self.label_44.setStyleSheet("image: url(img/cv.png);")
        self.label_45.setText(_translate("Dialog", "No Hp"))
        self.label_46.setText(_translate("Dialog", "Gender"))
        self.label_47.setText(_translate("Dialog", "Pasword"))
        self.radL.setText(_translate("Dialog", "Laki-laki"))
        self.radP.setText(_translate("Dialog", "Perempuan"))
        self.label_48.setText(_translate("Dialog", "Email"))
        self.label_49.setText(_translate("Dialog", "Nama"))
        self.label_50.setText(_translate("Dialog", "Alamat"))
        self.label_51.setText(_translate("Dialog", "Pekerjaan"))
        self.btnSimpanProfile.setText(_translate("Dialog", "Simpan Perubahan"))
        self.label_52.setText(_translate("Dialog", "Pengalaman Kerja"))
        self.label_53.setText(_translate("Dialog", "Keahlian"))
        ##Tampil Profile
        self.loadProfile(Dialog)
        ###

        self.Home_2.setTabText(self.Home_2.indexOf(self.Profile), _translate("Dialog", "             Profile             "))
        self.label_55.setText(_translate("Dialog", "No Lowongan"))
        self.label_56.setText(_translate("Dialog", "Unggah CV"))
        self.btnUnggahCV.setText(_translate("Dialog", "Unggah CV"))
        self.btnSubmitLamaran.setText(_translate("Dialog", "Submit"))
        self.label_57.setText(_translate("Dialog", "**Lihat nomor lowongan di menu home"))
        self.Home_2.setTabText(self.Home_2.indexOf(self.Lamaran), _translate("Dialog", "        Submit Lamaran        "))
        self.label_58.setText(_translate("Dialog", "Lihat kemajuan lamaran kamu.."))
        item = self.t_lamaran.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Id Submit"))
        item = self.t_lamaran.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Posisi"))
        item = self.t_lamaran.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Perusahaan"))
        item = self.t_lamaran.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Penempatan"))
        item = self.t_lamaran.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Tgl Submit"))
        item = self.t_lamaran.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Status"))
        #Tampil Data Lamaran
        #self.loadLamaran(Dialog)
        ####

        self.Home_2.setTabText(self.Home_2.indexOf(self.tab_3), _translate("Dialog", "       Daftar Lamaran      "))
        self.btnLogout.setText(_translate("Dialog", "Logout"))


    #-----------------------------FUNCTION-----------------------------#
    #---------------load data lowongan----------------#
    def loadLowongan(self, Dialog):
        _translate = QCoreApplication.translate
        query = QSqlQuery()
        no, posisi, perusahaan, penempatan, gaji, deadline = range(6)
        row = 0
        query.exec_('SELECT * FROM loker')
        while query.next() :
            for i in range(6):
                item = QTableWidgetItem()
                font = QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                #item.setText(str(query.value(i)))
                item.setText(_translate("Dialog", str(query.value(i))))
                self.tLowongan.setItem(row, i, item)
            row += 1
        item = QTableWidgetItem()

    #---------------load jumlah row lamaran----------------#
    def getRowCountLamaran(self):
        query = QSqlQuery()
        query.exec_('SELECT COUNT(*) FROM lamaran')
        query.next()
        rowCount = query.value(0)
        return rowCount

    #---------------load user id berdasarkan user loged in----------------#
    #def getIdAkun(self, getId):
        #iniid = getId
        #return iniid

    #---------------load data profile user loged in----------------#
    def loadProfile(self, getId):
        dapatId = getId
        idAkun, nama, email, alamat, password, hp, gender, pekerjaan, pengalaman, keahlian = range(10)
        query = QSqlQuery()
        query.exec_ ('''SELECT * FROM akun where id = '%s' ''' % (dapatId))
        while query.next():
            self.pNama.setText(str(query.value(nama)))
            self.pEmail.setText(str(query.value(email)))
            self.pAlamat.setText(str(query.value(alamat)))
            self.pPassword.setText(str(query.value(password)))
            self.pHp.setText(str(query.value(hp)))
            if query.value(gender) == 'Perempuan' :
                self.radP.setChecked(True)
                self.radL.setChecked(False)
            else:
                self.radP.setChecked(False)
                self.radL.setChecked(True)
            self.pHp_2.setText(str(query.value(pekerjaan)))
            self.pPengalaman.setText(str(query.value(pengalaman)))
            self.pSkill.setText(str(query.value(keahlian)))

    #---------------edit profile user----------------#
    def editProfile(self):
        dapatId = int(self.labelId.text())
        query = QSqlQuery()
        if self.radP.isChecked() :
            gender = 'Perempuan'
        else :
            gender = 'Laki-laki'
        query.exec_('''UPDATE akun SET nama = '%s', email = '%s', alamat = '%s', pass = '%s', hp = %d, gender = '%s', pekerjaan = '%s', pengalaman = '%s', keahlian = '%s' WHERE id = %d ''' %
            (self.pNama.text(),
            self.pEmail.text(), 
            self.pAlamat.toPlainText(),
            self.pPassword.text(),
            int(self.pHp.text()),
            gender,
            self.pHp_2.text(),
            self.pPengalaman.toPlainText(),
            self.pSkill.toPlainText(), 
            dapatId))
        QMessageBox.information(self, 'Update Berhasil', 'Profile berhasil diperbaharui')
        self.loadProfile(dapatId)

    #---------------add data lamaran berdasarkan user loged in----------------#
    def addLamaran(self):
        dapatId = int(self.labelId.text())
        posisi, perusahaan, penempatan, gaji = range(4)
        query1 = QSqlQuery()
        query1.exec_ ('''SELECT posisi, perusahaan, penempatan FROM loker WHERE no = %d ''' % int(self.subNo.text()))
        while query1.next():
            tposisi = str(query1.value(posisi))
            tperusahaan = str(query1.value(perusahaan))
            tpenempatan = str(query1.value(penempatan))
            tgl = date.today()
            noLam = self.getRowCountLamaran() + 1
            #cvFile = str(fname)
            #if not cvFile.open(QIODevice.ReadOnly) : 
            #    return
            #cv = cvFile.readAll()
            #data_tuple = (cv)
            query = QSqlQuery()
            query.exec_("INSERT INTO lamaran VALUES (%d, %d, '%s', '%s', '%s', '%s', 'Menunggu Interview', 'cv.pdf')" %
                    (noLam, dapatId, tposisi, tperusahaan, tpenempatan, tgl))
            QMessageBox.information(self, 'Submit Lamaran', 'Berhasil submit lamaran, tunggu pemberitahuan berikutnya')
            self.loadLamaran(dapatId)

    #---------------load data lamaran berdasarkan user loged in----------------#
    def loadLamaran(self, idAkun):
        dapatId = idAkun
        query = QSqlQuery()
        no, idAkun, posisi, perusahaan, penempatan, tglSubmit, status, cv = range(8)
        row = 0
        query.exec_('''SELECT noLam, posisi, perusahaan, penempatan, tglSubmit, status FROM lamaran where idAkun = '%s' ''' % (dapatId))
        while query.next() :
            for i in range(6):
                item = QTableWidgetItem()
                font = QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                item.setText(str(query.value(i)))
                self.t_lamaran.setItem(row, i, item)
            row += 1
        item = QTableWidgetItem()

    #---------------buka dialog open file----------------#
    def loadCV(self, Dialog):
        fname = QFileDialog.getOpenFileName(self, 'Open file', QDir.currentPath(), "Document files (*.jpg, *.pdf, *.docx *.png)")


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    #---------------connect database----------------#
    db = QSqlDatabase.addDatabase('QSQLITE')
    db.setDatabaseName('Lokerindo')
    if not db.open():
        print('ERROR: ' + db.lastError().text())
        sys.exit(1)

    #---------------menjalankan gui----------------#
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
