# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
from PyQt5.QtSql import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(-90, 0, 881, 551))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        #font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 85, 127);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(310, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        #font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_17.setObjectName("label_17")
        self.Home_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.Home_2.setGeometry(QtCore.QRect(0, 90, 791, 431))
        self.Home_2.setMinimumSize(QtCore.QSize(791, 431))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.Home_2.setFont(font)
        self.Home_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(85, 85, 255);")
        self.Home_2.setObjectName("Home_2")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.label_5 = QtWidgets.QLabel(self.Home)
        self.label_5.setGeometry(QtCore.QRect(80, 20, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        #font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_22 = QtWidgets.QLabel(self.Home)
        self.label_22.setGeometry(QtCore.QRect(80, 170, 161, 20))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.tLowongan = QtWidgets.QTableWidget(self.Home)
        self.tLowongan.setGeometry(QtCore.QRect(80, 70, 621, 261))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(75)
        self.tLowongan.setFont(font)
        self.tLowongan.setStyleSheet("color: rgb(85, 85, 255);\n"
"background-color: rgb(227, 227, 227);")
        self.tLowongan.setRowCount(11)
        self.tLowongan.setColumnCount(6)
        
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(5, item)
        self.Home_2.addTab(self.Home, "")
        self.Profile = QtWidgets.QWidget()
        self.Profile.setObjectName("Profile")
        self.label_33 = QtWidgets.QLabel(self.Profile)
        self.label_33.setGeometry(QtCore.QRect(30, 40, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        #font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.widget = QtWidgets.QWidget(self.Profile)
        self.widget.setGeometry(QtCore.QRect(140, 40, 301, 303))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.radL = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(75)
        self.radL.setFont(font)
        self.radL.setStyleSheet("color: rgb(255, 255, 255);")
        self.radL.setObjectName("radL")
        self.gridLayout_3.addWidget(self.radL, 5, 2, 1, 1)
        self.radP = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(75)
        self.radP.setFont(font)
        self.radP.setStyleSheet("color: rgb(255, 255, 255);")
        self.radP.setObjectName("radP")
        self.gridLayout_3.addWidget(self.radP, 5, 1, 1, 1)
        self.pAlamat = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pAlamat.setFont(font)
        self.pAlamat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pAlamat.setObjectName("pAlamat")
        self.gridLayout_3.addWidget(self.pAlamat, 2, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.pPassword = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pPassword.setFont(font)
        self.pPassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pPassword.setObjectName("pPassword")
        self.gridLayout_3.addWidget(self.pPassword, 3, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.pNama = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pNama.setFont(font)
        self.pNama.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pNama.setText("")
        self.pNama.setObjectName("pNama")
        self.gridLayout_3.addWidget(self.pNama, 0, 1, 1, 2)
        self.pEmail = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pEmail.setFont(font)
        self.pEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pEmail.setObjectName("pEmail")
        self.gridLayout_3.addWidget(self.pEmail, 1, 1, 1, 2)
        self.pHp = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pHp.setFont(font)
        self.pHp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pHp.setObjectName("pHp")
        self.gridLayout_3.addWidget(self.pHp, 4, 1, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.pHp_2 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pHp_2.setFont(font)
        self.pHp_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pHp_2.setObjectName("pHp_2")
        self.gridLayout_3.addWidget(self.pHp_2, 6, 1, 1, 2)
        self.btnSimpanProfile = QtWidgets.QPushButton(self.Profile)
        self.btnSimpanProfile.setGeometry(QtCore.QRect(580, 270, 152, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        #font.setBold(False)
        font.setWeight(50)
        self.btnSimpanProfile.setFont(font)
        self.btnSimpanProfile.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnSimpanProfile.setObjectName("btnSimpanProfile")
        self.btnSimpanProfile.clicked.connect(self.editProfile)


        self.widget1 = QtWidgets.QWidget(self.Profile)
        self.widget1.setGeometry(QtCore.QRect(470, 40, 258, 211))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.pPengalaman = QtWidgets.QTextEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pPengalaman.setFont(font)
        self.pPengalaman.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pPengalaman.setObjectName("pPengalaman")
        self.gridLayout_2.addWidget(self.pPengalaman, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        #font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.pSkill = QtWidgets.QTextEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pSkill.setFont(font)
        self.pSkill.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pSkill.setObjectName("pSkill")
        self.gridLayout_2.addWidget(self.pSkill, 3, 0, 1, 1)

        self.Home_2.addTab(self.Profile, "")
        self.Lamaran = QtWidgets.QWidget()
        self.Lamaran.setObjectName("Lamaran")
        self.label_27 = QtWidgets.QLabel(self.Lamaran)
        self.label_27.setGeometry(QtCore.QRect(80, 90, 241, 231))
        self.label_27.setStyleSheet("image: url(img/signup.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.layoutWidget = QtWidgets.QWidget(self.Lamaran)
        self.layoutWidget.setGeometry(QtCore.QRect(371, 112, 252, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        #font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 0, 0, 1, 1)
        self.subNo = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.subNo.setFont(font)
        self.subNo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.subNo.setText("")
        self.subNo.setObjectName("subNo")
        self.gridLayout.addWidget(self.subNo, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        #font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 1, 0, 1, 1)
        self.btnUnggahCV = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        self.btnUnggahCV.setFont(font)
        self.btnUnggahCV.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnUnggahCV.setObjectName("btnUnggahCV")
        self.gridLayout.addWidget(self.btnUnggahCV, 1, 1, 1, 1)
        self.btnSubmitLamaran = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(13)
        #font.setBold(False)
        font.setWeight(50)
        self.btnSubmitLamaran.setFont(font)
        self.btnSubmitLamaran.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnSubmitLamaran.setObjectName("btnSubmitLamaran")
        self.gridLayout.addWidget(self.btnSubmitLamaran, 2, 0, 1, 2)
        self.btnSubmitLamaran.clicked.connect(self.addLamaran)

        self.label_36 = QtWidgets.QLabel(self.Lamaran)
        self.label_36.setGeometry(QtCore.QRect(370, 220, 251, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        #font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_36.setObjectName("label_36")
        self.Home_2.addTab(self.Lamaran, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(80, 20, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        #font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.t_lamaran = QtWidgets.QTableWidget(self.tab)
        self.t_lamaran.setGeometry(QtCore.QRect(80, 70, 621, 261))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(11)
        self.t_lamaran.setFont(font)
        self.t_lamaran.setStyleSheet("color: rgb(85, 85, 255);\n"
"background-color: rgb(227, 227, 227);")
        self.t_lamaran.setRowCount(11)
        self.t_lamaran.setColumnCount(6)
        self.t_lamaran.setObjectName("t_lamaran")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.t_lamaran.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.t_lamaran.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        #font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_lamaran.setHorizontalHeaderItem(5, item)
        self.Home_2.addTab(self.tab, "")
        self.btnLogout = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogout.setGeometry(QtCore.QRect(700, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        #font.setBold(True)
        font.setWeight(75)
        self.btnLogout.setFont(font)
        self.btnLogout.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.btnLogout.setObjectName("btnLogout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Home_2.setCurrentIndex(2)
        self.btnLogout.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_17.setText(_translate("MainWindow", "LOKERINDO"))
        self.label_5.setText(_translate("MainWindow", "Ayo, cari pekerjaan sesuai keahlian kamu di sini....!"))
        item = self.tLowongan.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No Lowongan"))
        item = self.tLowongan.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Posisi"))
        item = self.tLowongan.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Perusahaan"))
        item = self.tLowongan.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Penempatan"))
        item = self.tLowongan.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gaji Ditawarkan"))
        item = self.tLowongan.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Max Submit"))
        #Tampil Data Lowongan
        self.loadLowongan(MainWindow)
        ####

        self.Home_2.setTabText(self.Home_2.indexOf(self.Home), _translate("MainWindow", "             Home          ", " "))
        self.label_33.setText(_translate("MainWindow", "     Foto"))
        self.label_14.setText(_translate("MainWindow", "No Hp"))
        self.label_15.setText(_translate("MainWindow", "Gender"))
        self.label_12.setText(_translate("MainWindow", "Pasword"))
        self.radL.setText(_translate("MainWindow", "Laki-laki"))
        self.radP.setText(_translate("MainWindow", "Perempuan"))
        self.label_9.setText(_translate("MainWindow", "Email"))
        self.label_13.setText(_translate("MainWindow", "Nama"))
        self.label_10.setText(_translate("MainWindow", "Alamat"))
        self.label_19.setText(_translate("MainWindow", "Pekerjaan"))
        self.btnSimpanProfile.setText(_translate("MainWindow", "Simpan Perubahan"))
        self.label_11.setText(_translate("MainWindow", "Pengalaman Kerja"))
        self.label_18.setText(_translate("MainWindow", "Keahlian"))
        ##Tampil Profile
        self.loadProfile(MainWindow)
        ###
        self.Home_2.setTabText(self.Home_2.indexOf(self.Profile), _translate("MainWindow", "             Profile             "))
        self.label_34.setText(_translate("MainWindow", "No Lowongan"))
        self.label_35.setText(_translate("MainWindow", "Unggah CV"))
        self.btnUnggahCV.setText(_translate("MainWindow", "Unggah CV"))
        self.btnSubmitLamaran.setText(_translate("MainWindow", "Submit"))
        self.label_36.setText(_translate("MainWindow", "**Lihat nomor lowongan di menu home"))
        self.Home_2.setTabText(self.Home_2.indexOf(self.Lamaran), _translate("MainWindow", "        Submit Lamaran        "))
        self.label_6.setText(_translate("MainWindow", "Lihat kemajuan lamaran kamu.."))
        item = self.t_lamaran.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.t_lamaran.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Posisi"))
        item = self.t_lamaran.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Perusahaan"))
        item = self.t_lamaran.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Penempatan"))
        item = self.t_lamaran.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tgl Submit"))
        item = self.t_lamaran.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        #Tampil Data Lamaran
        self.loadLamaran(MainWindow)
        ####

        self.Home_2.setTabText(self.Home_2.indexOf(self.tab), _translate("MainWindow", "       Daftar Lamaran      "))
        self.btnLogout.setText(_translate("MainWindow", "Keluar"))

    def loadLowongan(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        query = QSqlQuery()
        no, posisi, perusahaan, penempatan, gaji, deadline = range(6)
        row = 0
        query.exec_('SELECT * FROM loker')
        while query.next() :
            for i in range(6):
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                #item.setText(str(query.value(i)))
                item.setText(_translate("MainWindow", str(query.value(i))))
                self.tLowongan.setItem(row, i, item)
            row += 1
        item = QtWidgets.QTableWidgetItem()

    def getRowCountLamaran(self, MainWindow):
        query = QSqlQuery()
        query.exec_('SELECT COUNT(*) FROM lamaran')
        query.next()
        rowCount = query.value(0)
        return rowCount

    def loadProfile(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        idAkun, nama, email, alamat, password, hp, gender, pekerjaan, pengalaman, keahlian = range(10)
        query = QSqlQuery()
        query.exec_ ('SELECT * FROM akun')
        while query.next():
            self.pNama.setText(_translate("MainWindow", str(query.value(nama))))
            self.pEmail.setText(_translate("MainWindow", str(query.value(email))))
            self.pAlamat.setText(_translate("MainWindow", str(query.value(alamat))))
            self.pPassword.setText(_translate("MainWindow", str(query.value(password))))
            self.pHp.setText(_translate("MainWindow", str(query.value(hp))))
            if query.value(gender) == 'Perempuan' :
                self.radP.setChecked(True)
                self.radL.setChecked(False)
            else:
                self.radP.setChecked(False)
                self.radL.setChecked(True)
            self.pHp_2.setText(_translate("MainWindow", str(query.value(pekerjaan))))
            self.pPengalaman.setText(_translate("MainWindow", str(query.value(pengalaman))))
            self.pSkill.setText(_translate("MainWindow", str(query.value(keahlian))))

    def editProfile(self):
        query = QSqlQuery()
        id = 1
        if self.radP.isChecked() :
            gender = 'Perempuan'
        else :
            gender = 'Laki-laki'
        query.exec_('''UPDATE akun SET nama = '%s', email = '%s', alamat = '%s', pass = '%s', hp = %d, gender = '%s', pekerjaan = '%s', pengalaman = '%s', keahlian = '%s' WHERE id = %d ''' %
            (self.pNama.text(),
            self.pEmail.text(), 
            self.pAlamat.toPlainText(),
            self.pPassword.text(),
            int(self.pHp.text()),
            gender,
            self.pHp_2.text(),
            self.pPengalaman.toPlainText(),
            self.pSkill.toPlainText(), id))
        #QtWidgets.QMessageBox.information(self, 'Update Berhasil', 'Profile berhasil diperbaharui', QtWidgets.QMessageBox.Ok)
        self.loadProfile(MainWindow)

    def addLamaran(self):
        posisi, perusahaan, penempatan, gaji = range(4)
        query1 = QSqlQuery()
        query1.exec_ ('''SELECT posisi, perusahaan, penempatan FROM loker WHERE no = %d ''' % int(self.subNo.text()))
        while query1.next():
            tposisi = str(query1.value(posisi))
            tperusahaan = str(query1.value(perusahaan))
            tpenempatan = str(query1.value(penempatan))
            tgl = date.today()
            noLam = self.getRowCountLamaran(MainWindow) + 1
            idAkun = 1
            query = QSqlQuery()
            query.exec_("INSERT INTO lamaran VALUES (%d, %d, '%s', '%s', '%s', '%s', 'Menunggu Interview','CV.pdf')" %
                    (noLam, idAkun, tposisi, tperusahaan, tpenempatan, tgl))
            self.loadLamaran(MainWindow)

    def loadLamaran(self,MainWindow):
        _translate = QtCore.QCoreApplication.translate
        query = QSqlQuery()
        no, idAkun, posisi, perusahaan, penempatan, tglSubmit, status, cv = range(8)
        row = 0
        query.exec_('SELECT noLam, posisi, perusahaan, penempatan, tglSubmit, status FROM lamaran')
        while query.next() :
            for i in range(6):
                item = QtWidgets.QTableWidgetItem()
                font = QtGui.QFont()
                font.setFamily("Segoe UI Light")
                font.setPointSize(9)
                item.setFont(font)
                #item.setText(str(query.value(i)))
                item.setText(_translate("MainWindow", str(query.value(i))))
                self.t_lamaran.setItem(row, i, item)
            row += 1
        item = QtWidgets.QTableWidgetItem()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    db = QSqlDatabase.addDatabase('QSQLITE')
    db.setDatabaseName('Lokerindo')
    if not db.open():
        print('ERROR: ' + db.lastError().text())
        sys.exit(1)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
