import sys
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtSql import *

class MainForm(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        #self.loadDataLoker()
    
    def setupUi(self):
        self.resize(785, 569)
        #backgound putih
        self.centralwidget = QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setGeometry(QRect(-90, 0, 881, 551))
        font = QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 85, 127);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")

        #JUDUL
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setGeometry(QRect(310, 20, 171, 51))
        font = QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_17.setText("LOKERINDO")
        self.label_17.setObjectName("label_17")

        #tab homepage
        self.Home_2 = QTabWidget(self.centralwidget)
        self.Home_2.setGeometry(QRect(0, 90, 791, 431))
        self.Home_2.setMinimumSize(QSize(791, 431))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Home_2.setFont(font)
        self.Home_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(85, 85, 255);")
        self.Home_2.setObjectName("Home_2")
        self.Home = QWidget()
        self.Home.setObjectName("Home")
        self.label_5 = QLabel(self.Home)
        self.label_5.setGeometry(QRect(80, 20, 481, 41))
        font = QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setText("Ayo, cari pekerjaan sesuai keahlian kamu di sini....!")
        self.label_5.setObjectName("label_5")
        self.label_22 = QLabel(self.Home)
        self.label_22.setGeometry(QRect(80, 170, 161, 20))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.tLowongan = QTableWidget(self.Home)
        self.tLowongan.setGeometry(QRect(80, 70, 621, 261))
        font = QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tLowongan.setFont(font)
        self.tLowongan.setStyleSheet("color: rgb(85, 85, 255);\n"
"background-color: rgb(227, 227, 227);")
        self.tLowongan.setRowCount(11)
        self.tLowongan.setColumnCount(6)
        self.tLowongan.setObjectName("tLowongan")
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        item.setFont(font)
        self.tLowongan.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.tLowongan.setVerticalHeaderItem(10, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily("Segoe UI Light")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tLowongan.setHorizontalHeaderItem(5, item)

if __name__ == '__main__':
    a = QApplication(sys.argv)
    db = QSqlDatabase.addDatabase('QSQLITE')
    db.setDatabaseName('Loker')
    if not db.open():
        print('ERROR: ' + db.lastError().text())
        sys.exit(1)
    form = MainForm()
    form.show()
    a.exec_()