# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(-20, -8, 821, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 85, 127);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.Login = QtWidgets.QTabWidget(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(0, 80, 791, 431))
        self.Login.setMinimumSize(QtCore.QSize(761, 431))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Login.setFont(font)
        self.Login.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(85, 85, 255);")
        self.Login.setObjectName("Login")
        self.Menu = QtWidgets.QWidget()
        self.Menu.setObjectName("Menu")
        self.label = QtWidgets.QLabel(self.Menu)
        self.label.setGeometry(QtCore.QRect(370, 20, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.btnHomeCari = QtWidgets.QPushButton(self.Menu)
        self.btnHomeCari.setGeometry(QtCore.QRect(370, 320, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnHomeCari.setFont(font)
        self.btnHomeCari.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnHomeCari.setObjectName("btnHomeCari")
        self.layoutWidget = QtWidgets.QWidget(self.Menu)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 100, 351, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_8 = QtWidgets.QLabel(self.Menu)
        self.label_8.setGeometry(QtCore.QRect(0, 100, 311, 221))
        self.label_8.setStyleSheet("image: url(img/image 372.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.layoutWidget1 = QtWidgets.QWidget(self.Menu)
        self.layoutWidget1.setGeometry(QtCore.QRect(300, 100, 61, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_29.setStyleSheet("image: url(img/wallet.png);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_7.addWidget(self.label_29)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("image: url(img/startup.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setStyleSheet("image: url(img/work.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setStyleSheet("image: url(img/world.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_28 = QtWidgets.QLabel(self.Menu)
        self.label_28.setGeometry(QtCore.QRect(10, 130, 271, 191))
        self.label_28.setStyleSheet("image: url(img/City.png);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_3 = QtWidgets.QLabel(self.Menu)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.Login.addTab(self.Menu, "")
        self.Menu_2 = QtWidgets.QWidget()
        self.Menu_2.setObjectName("Menu_2")
        self.label_5 = QtWidgets.QLabel(self.Menu_2)
        self.label_5.setGeometry(QtCore.QRect(380, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.btnDaftar = QtWidgets.QPushButton(self.Menu_2)
        self.btnDaftar.setGeometry(QtCore.QRect(330, 350, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnDaftar.setFont(font)
        self.btnDaftar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnDaftar.setObjectName("btnDaftar")
        self.layoutWidget2 = QtWidgets.QWidget(self.Menu_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(330, 80, 91, 221))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.layoutWidget_2 = QtWidgets.QWidget(self.Menu_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(430, 280, 301, 26))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radL = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radL.setFont(font)
        self.radL.setStyleSheet("color: rgb(255, 255, 255);")
        self.radL.setObjectName("radL")
        self.horizontalLayout.addWidget(self.radL)
        self.radP = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radP.setFont(font)
        self.radP.setStyleSheet("color: rgb(255, 255, 255);")
        self.radP.setObjectName("radP")
        self.horizontalLayout.addWidget(self.radP)
        self.layoutWidget_3 = QtWidgets.QWidget(self.Menu_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(430, 80, 301, 191))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.daftarNama = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.daftarNama.setFont(font)
        self.daftarNama.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.daftarNama.setObjectName("daftarNama")
        self.verticalLayout.addWidget(self.daftarNama)
        self.daftarEmail = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.daftarEmail.setFont(font)
        self.daftarEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.daftarEmail.setObjectName("daftarEmail")
        self.verticalLayout.addWidget(self.daftarEmail)
        self.daftarPassword = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.daftarPassword.setFont(font)
        self.daftarPassword.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.daftarPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.daftarPassword.setObjectName("daftarPassword")
        self.verticalLayout.addWidget(self.daftarPassword)
        self.daftarAlamat = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.daftarAlamat.setFont(font)
        self.daftarAlamat.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.daftarAlamat.setObjectName("daftarAlamat")
        self.verticalLayout.addWidget(self.daftarAlamat)
        self.daftarHp = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.daftarHp.setFont(font)
        self.daftarHp.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.daftarHp.setObjectName("daftarHp")
        self.verticalLayout.addWidget(self.daftarHp)
        self.checkData = QtWidgets.QCheckBox(self.Menu_2)
        self.checkData.setGeometry(QtCore.QRect(570, 320, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.checkData.setFont(font)
        self.checkData.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkData.setObjectName("checkData")
        self.label_15 = QtWidgets.QLabel(self.Menu_2)
        self.label_15.setGeometry(QtCore.QRect(20, 300, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_22 = QtWidgets.QLabel(self.Menu_2)
        self.label_22.setGeometry(QtCore.QRect(80, 170, 161, 20))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.Menu_2)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 301, 211))
        self.label_27.setStyleSheet("image: url(img/signup.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.Login.addTab(self.Menu_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(290, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.btnLogin = QtWidgets.QPushButton(self.tab)
        self.btnLogin.setGeometry(QtCore.QRect(240, 210, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnLogin.setObjectName("btnLogin")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(240, 270, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.btnBuat = QtWidgets.QPushButton(self.tab)
        self.btnBuat.setGeometry(QtCore.QRect(440, 260, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnBuat.setFont(font)
        self.btnBuat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.btnBuat.setObjectName("btnBuat")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(340, 110, 231, 91))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loginEmail = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.loginEmail.setFont(font)
        self.loginEmail.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.loginEmail.setObjectName("loginEmail")
        self.verticalLayout_5.addWidget(self.loginEmail)
        self.loginPassword = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        self.loginPassword.setFont(font)
        self.loginPassword.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.loginPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPassword.setObjectName("loginPassword")
        self.verticalLayout_5.addWidget(self.loginPassword)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(240, 120, 88, 71))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.Login.addTab(self.tab, "")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(320, 20, 171, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Login.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Homepage", "Homepage"))
        self.label.setText(_translate("MainWindow", "Lowongan Kerja Indonesia"))
        self.btnHomeCari.setText(_translate("MainWindow", "CARI LOKER SEKARANG"))
        self.label_6.setText(_translate("MainWindow", "Bayar pendaftaran setelah terima Job"))
        self.label_18.setText(_translate("MainWindow", "Perusahaan Berkualitas"))
        self.label_7.setText(_translate("MainWindow", "Lowongan kerja beragam"))
        self.label_19.setText(_translate("MainWindow", "Lowongan tersebar diberbagai Kota"))
        self.label_3.setText(_translate("MainWindow", "LOKERINDO\n"
"Membantu menemukan karier\n"
"dengan mudah, hemat dan cepat"))
        self.Login.setTabText(self.Login.indexOf(self.Menu), _translate("MainWindow", "                      Homepage                      "))
        self.label_5.setText(_translate("MainWindow", "Silahkan Isi Data Anda"))
        self.btnDaftar.setText(_translate("MainWindow", "DAFTAR"))
        self.label_9.setText(_translate("MainWindow", "Nama"))
        self.label_10.setText(_translate("MainWindow", "Email"))
        self.label_11.setText(_translate("MainWindow", "Pasword"))
        self.label_13.setText(_translate("MainWindow", "Alamat"))
        self.label_14.setText(_translate("MainWindow", "No Hp"))
        self.label_12.setText(_translate("MainWindow", "Gender"))
        self.radL.setText(_translate("MainWindow", "Laki-laki"))
        self.radP.setText(_translate("MainWindow", "Perempuan"))
        self.checkData.setText(_translate("MainWindow", "Apakah Data Sudah Tepat ?"))
        self.label_15.setText(_translate("MainWindow", "Segera daftar dan dapatkan job sesuai\n"
"            pasion dan keahlianmu"))
        self.Login.setTabText(self.Login.indexOf(self.Menu_2), _translate("MainWindow", "                        Daftar                       ", " "))
        self.label_23.setText(_translate("MainWindow", "Selamat Datang"))
        self.btnLogin.setText(_translate("MainWindow", "Masuk"))
        self.label_26.setText(_translate("MainWindow", "Belum memiliki akun ?"))
        self.btnBuat.setText(_translate("MainWindow", "Buat Akun"))
        self.label_24.setText(_translate("MainWindow", "Email"))
        self.label_25.setText(_translate("MainWindow", "Pasword"))
        self.Login.setTabText(self.Login.indexOf(self.tab), _translate("MainWindow", "                        Masuk                        "))
        self.label_17.setText(_translate("MainWindow", "LOKERINDO"))
#import sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
